"""Initial schema

Revision ID: c9a47ade3b2f
Revises: 
Create Date: 2026-08-04 21:11:02.885058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a47ade3b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('extra_permissions', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('platform_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('remote_id', sa.String(length=128), nullable=True),
    sa.Column('remote_handle', sa.String(length=128), nullable=True),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'remote_id', name='uq_account_platform_remote')
    )
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_accounts_platform'), ['platform'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signals_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trends', schema=None) as batch_op:
        batch_op.create_index('ix_trend_platform_captured', ['platform', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trends_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trends_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_trends_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_trends_status'), ['status'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('category_id', sa.String(length=8), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('privacy', sa.String(length=16), nullable=True),
    sa.Column('made_for_kids', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_shorts_ready', sa.Boolean(), nullable=False),
    sa.Column('format_notes', sa.Text(), nullable=True),
    sa.Column('license_type', sa.String(length=24), nullable=False),
    sa.Column('license_source', sa.String(length=255), nullable=True),
    sa.Column('license_reference', sa.String(length=255), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('rights_confirmed', sa.Boolean(), nullable=False),
    sa.Column('rights_confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('rights_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rights_confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_status'), ['status'], unique=False)

    op.create_table('stat_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('remote_id', sa.String(length=128), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=False),
    sa.Column('comments', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('favorites', sa.BigInteger(), nullable=False),
    sa.Column('watch_time_minutes', sa.Float(), nullable=False),
    sa.Column('average_view_percentage', sa.Float(), nullable=True),
    sa.Column('subscribers_gained', sa.BigInteger(), nullable=False),
    sa.Column('estimated_revenue', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_stat_account_captured', ['account_id', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_snapshots_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_snapshots_remote_id'), ['remote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_snapshots_video_id'), ['video_id'], unique=False)
        batch_op.create_index('ix_stat_video_captured', ['video_id', 'captured_at'], unique=False)

    op.create_table('upload_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('resumable_uri', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('remote_id', sa.String(length=128), nullable=True),
    sa.Column('remote_url', sa.String(length=512), nullable=True),
    sa.Column('is_automatic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_jobs_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_jobs_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_jobs_remote_id'), ['remote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_jobs_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_jobs_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_jobs_video_id'))
        batch_op.drop_index(batch_op.f('ix_upload_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_upload_jobs_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_upload_jobs_remote_id'))
        batch_op.drop_index(batch_op.f('ix_upload_jobs_platform'))
        batch_op.drop_index(batch_op.f('ix_upload_jobs_account_id'))

    op.drop_table('upload_jobs')
    with op.batch_alter_table('stat_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_stat_video_captured')
        batch_op.drop_index(batch_op.f('ix_stat_snapshots_video_id'))
        batch_op.drop_index(batch_op.f('ix_stat_snapshots_remote_id'))
        batch_op.drop_index(batch_op.f('ix_stat_snapshots_platform'))
        batch_op.drop_index(batch_op.f('ix_stat_snapshots_captured_at'))
        batch_op.drop_index(batch_op.f('ix_stat_snapshots_account_id'))
        batch_op.drop_index('ix_stat_account_captured')

    op.drop_table('stat_snapshots')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_status'))

    op.drop_table('videos')
    with op.batch_alter_table('trends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trends_status'))
        batch_op.drop_index(batch_op.f('ix_trends_region'))
        batch_op.drop_index(batch_op.f('ix_trends_platform'))
        batch_op.drop_index(batch_op.f('ix_trends_captured_at'))
        batch_op.drop_index('ix_trend_platform_captured')

    op.drop_table('trends')
    op.drop_table('settings')
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_accounts_platform'))

    op.drop_table('platform_accounts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    # ### end Alembic commands ###
